### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by pawelklimek** [Piffek/shelter-microservices#1]
jest ok, 
ale łatwo się pogubić z tymi nazwami

daj do env. tez porty wyjściowe bo teraz mamy 2 miejsca skąd są brane zmienne env i sam compose.

np.
    ports:
      - "${PET_MYSQL_PORT}:3306"

doprecyzowałbym nazwy bo łatwo się pogubić.

ja bym to tak napisał
```
  pet-service-db:
    image: pet-service-db
    build:
      dockerfile: pet-service-db/Dockerfile
      args:
        - MY_DATABASE_NAME=${PET_MYSQL_DATABASE}
        - MY_USER=${PET_MYSQL_USER}
        - MY_PASSWORD=${PET_MYSQL_PASSWORD}
        - MY_ROOT_PASSWORD=${PET_MYSQL_ROOT_PASSWORD}
    ports:
      - "${PET_MYSQL_PORT}:3306"

```
z taka stuktura od razu łatwiej ogarnąc który kontener co reprezentuje

<img width="242" alt="image" src="https://github.com/Piffek/shelter-microservices/assets/20891862/d56fc0de-81ac-4c88-affc-90ab25929254">
